# Generated by Django 3.0.5 on 2020-04-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iowagolfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_location', models.CharField(max_length=100)),
                ('image_url', models.CharField(default='', max_length=512)),
                ('hole_1_par', models.IntegerField()),
                ('hole_2_par', models.IntegerField()),
                ('hole_3_par', models.IntegerField()),
                ('hole_4_par', models.IntegerField()),
                ('hole_5_par', models.IntegerField()),
                ('hole_6_par', models.IntegerField()),
                ('hole_7_par', models.IntegerField()),
                ('hole_8_par', models.IntegerField()),
                ('hole_9_par', models.IntegerField()),
                ('hole_10_par', models.IntegerField()),
                ('hole_11_par', models.IntegerField()),
                ('hole_12_par', models.IntegerField()),
                ('hole_13_par', models.IntegerField()),
                ('hole_14_par', models.IntegerField()),
                ('hole_15_par', models.IntegerField()),
                ('hole_16_par', models.IntegerField()),
                ('hole_17_par', models.IntegerField()),
                ('hole_18_par', models.IntegerField()),
                ('front_9_par', models.IntegerField()),
                ('back_9_par', models.IntegerField()),
                ('full_18_par', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='fullname',
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='handicap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='user_name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_1_score', models.IntegerField()),
                ('hole_2_score', models.IntegerField()),
                ('hole_3_score', models.IntegerField()),
                ('hole_4_score', models.IntegerField()),
                ('hole_5_score', models.IntegerField()),
                ('hole_6_score', models.IntegerField()),
                ('hole_7_score', models.IntegerField()),
                ('hole_8_score', models.IntegerField()),
                ('hole_9_score', models.IntegerField()),
                ('hole_10_score', models.IntegerField()),
                ('hole_11_score', models.IntegerField()),
                ('hole_12_score', models.IntegerField()),
                ('hole_13_score', models.IntegerField()),
                ('hole_14_score', models.IntegerField()),
                ('hole_15_score', models.IntegerField()),
                ('hole_16_score', models.IntegerField()),
                ('hole_17_score', models.IntegerField()),
                ('hole_18_score', models.IntegerField()),
                ('front_9_score', models.IntegerField()),
                ('back_9_score', models.IntegerField()),
                ('full_18_score', models.IntegerField()),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursename', to='Iowagolfapp.Course')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='Iowagolfapp.Player')),
            ],
        ),
    ]
