# Generated by Django 3.0.5 on 2020-04-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iowagolfapp', '0003_auto_20200416_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='coursename',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
