# Generated by Django 3.0.5 on 2020-04-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iowagolfapp', '0004_auto_20200417_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='coursename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursename', to='Iowagolfapp.Course'),
        ),
        migrations.AlterField(
            model_name='score',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='Iowagolfapp.Player'),
        ),
    ]
